version: "1"

services:
  postgres:
    image: bitnami/postgresql:15
    restart: no
    hostname: postgres
    container_name: end2end
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=end2end
      - POSTGRESQL_DATABASE=end2end_zadatak
      - POSTGRESQL_WAL_LEVEL=logical
    ports:
      - "5432:5432"
